/// Card types returned by Laya from the backend
enum CardType {
  concept,
  quiz,
  didYouKnow,
  challenge,
  answerReveal,
  achievement,
}

/// A single learning card generated by Laya
class StudyCard {
  final String id;
  final String sessionId;
  final CardType cardType;
  final String question;
  final String? answer;
  final List<String>? choices;
  final String? correctChoice;
  final String? explanation;
  final int position;
  final CardResult result;

  const StudyCard({
    required this.id,
    required this.sessionId,
    required this.cardType,
    required this.question,
    this.answer,
    this.choices,
    this.correctChoice,
    this.explanation,
    required this.position,
    this.result = CardResult.pending,
  });

  factory StudyCard.fromJson(Map<String, dynamic> json) {
    return StudyCard(
      id: json['id'] as String,
      sessionId: json['session_id'] as String,
      cardType: _parseCardType(json['card_type'] as String),
      question: json['question'] as String,
      answer: json['answer'] as String?,
      choices: json['choices'] != null
          ? (json['choices'] as List<dynamic>).cast<String>()
          : null,
      correctChoice: json['correct_choice'] as String?,
      explanation: json['explanation'] as String?,
      position: json['position'] as int,
      result: _parseResult(json['result'] as String? ?? 'pending'),
    );
  }

  StudyCard copyWith({CardResult? result}) {
    return StudyCard(
      id: id,
      sessionId: sessionId,
      cardType: cardType,
      question: question,
      answer: answer,
      choices: choices,
      correctChoice: correctChoice,
      explanation: explanation,
      position: position,
      result: result ?? this.result,
    );
  }

  static CardType _parseCardType(String type) {
    switch (type) {
      case 'concept': return CardType.concept;
      case 'quiz': return CardType.quiz;
      case 'did_you_know': return CardType.didYouKnow;
      case 'challenge': return CardType.challenge;
      case 'answer_reveal': return CardType.answerReveal;
      case 'achievement': return CardType.achievement;
      default: return CardType.concept;
    }
  }

  static CardResult _parseResult(String result) {
    switch (result) {
      case 'correct': return CardResult.correct;
      case 'wrong': return CardResult.wrong;
      case 'skipped': return CardResult.skipped;
      default: return CardResult.pending;
    }
  }

  String get cardTypeLabel {
    switch (cardType) {
      case CardType.concept: return 'Concept';
      case CardType.quiz: return 'Quiz';
      case CardType.didYouKnow: return 'Did You Know?';
      case CardType.challenge: return 'Challenge';
      case CardType.answerReveal: return 'Answer';
      case CardType.achievement: return 'Achievement!';
    }
  }
}

enum CardResult { pending, correct, wrong, skipped }
