-- ============================================================
--  ALALAi Database Schema
--  Philippine Standard Time (UTC+8)
-- ============================================================

CREATE DATABASE IF NOT EXISTS alalayai
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE alalayai;

-- ── Topics (pre-loaded DepEd materials) ──────────────────
CREATE TABLE IF NOT EXISTS topics (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  subject     VARCHAR(50)  NOT NULL,          -- math, science, filipino, english, araling_panlipunan
  grade_level TINYINT      NOT NULL,          -- 1–12
  title       VARCHAR(255) NOT NULL,
  description TEXT,
  content     LONGTEXT     NOT NULL,          -- raw lesson text Laya uses
  language    VARCHAR(10)  NOT NULL DEFAULT 'mixed', -- filipino, english, mixed
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_subject_grade (subject, grade_level)
);

-- ── Sessions (one study session per swipe deck) ──────────
CREATE TABLE IF NOT EXISTS sessions (
  id              VARCHAR(36)  PRIMARY KEY,   -- UUID
  topic_id        INT          NULL,          -- NULL if user uploaded their own file
  grade_level     TINYINT      NOT NULL,
  subject         VARCHAR(50)  NOT NULL,
  language        VARCHAR(10)  NOT NULL DEFAULT 'mixed',
  total_cards     INT          NOT NULL DEFAULT 0,
  cards_correct   INT          NOT NULL DEFAULT 0,
  cards_wrong     INT          NOT NULL DEFAULT 0,
  cards_skipped   INT          NOT NULL DEFAULT 0,
  status          ENUM('active','completed','abandoned') NOT NULL DEFAULT 'active',
  started_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at    TIMESTAMP    NULL,
  FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE SET NULL
);

-- ── Cards (generated by Laya for a session) ──────────────
CREATE TABLE IF NOT EXISTS cards (
  id           VARCHAR(36)  PRIMARY KEY,      -- UUID
  session_id   VARCHAR(36)  NOT NULL,
  card_type    ENUM(
    'concept',
    'quiz',
    'did_you_know',
    'challenge',
    'answer_reveal',
    'achievement'
  ) NOT NULL,
  question     TEXT         NOT NULL,
  answer       TEXT         NULL,
  choices      JSON         NULL,             -- for quiz cards: ["A","B","C","D"]
  correct_choice VARCHAR(5) NULL,             -- "A", "B", "C", or "D"
  explanation  TEXT         NULL,
  position     INT          NOT NULL DEFAULT 0,
  result       ENUM('correct','wrong','skipped','pending') NOT NULL DEFAULT 'pending',
  created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
  INDEX idx_session (session_id)
);

-- ── Chat messages (Laya conversation log) ────────────────
CREATE TABLE IF NOT EXISTS chat_messages (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(36)  NOT NULL,
  role       ENUM('user','assistant') NOT NULL,
  content    TEXT         NOT NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
  INDEX idx_session_chat (session_id)
);